#
# IIS2MDC makefile
# Philipp Schilk, 2022
# Free to use with no restrictions but no guarantees.
#

################################################################################
#               ____  _____ _____ _____ ___ _   _  ____ ____
#              / ___|| ____|_   _|_   _|_ _| \ | |/ ___/ ___|
#              \___ \|  _|   | |   | |  | ||  \| | |  _\___ \
#               ___) | |___  | |   | |  | || |\  | |_| |___) |
#              |____/|_____| |_|   |_| |___|_| \_|\____|____/
#
#################################################################################

# Reginald commit to use:
REGINALD_COMMIT_LOCK=80ee99a

# Files generated by reginald:
REGINALD_OUTPUT_FILES= inc/iis2mdc_regs.h inc/iis2mdc_enums.h inc/iis2mdc_reg_utils.h

# Reginald location:
REGINALD_REPO=scripts/reginald
REGINALD=$(REGINALD_REPO)/run.py
REGINALD_PYTHON=$(REGINALD_REPO)/env/bin/python


################################################################################
#                   _   _ _____ ___ _     ___ _______   __
#                  | | | |_   _|_ _| |   |_ _|_   _\ \ / /
#                  | | | | | |  | || |    | |  | |  \ V /
#                  | |_| | | |  | || |___ | |  | |   | |
#                   \___/  |_| |___|_____|___| |_|   |_|
#
################################################################################

.PHONY: all
all: $(REGINALD_OUTPUT_FILES)

.PHONY: clean
clean:
	rm $(REGINALD_OUTPUT_FILES)
	rm $(REGINALD_REPO) -rf

.PHONY: format
format:
	python3 scripts/clang_format.py

# Generate documentation using doxygen:
.PHONY: doc
doc:
	doxygen
	firefox doc/html/index.html

# Generate register header files using reginald:
.PHONY: $(REGINALD_OUTPUT_FILES)
$(REGINALD_OUTPUT_FILES) &: iis2mdc_regs.yaml $(REGINALD)
	$(SILENT) $(REGINALD_PYTHON) $(REGINALD) iis2mdc_regs.yaml c.funcpack inc/ --no-field-enum-prefix
	$(SILENT) clang-format -i -style=file $(REGINALD_OUTPUT_FILES)

# Setup the correct version of reginald:
$(REGINALD): | $(REGINALD_REPO)
	@echo ""
	@echo "==== Installing Reginald: Reginald checkout... =========================================="
	@echo ""
	$(SILENT) git -C $(REGINALD_REPO) checkout $(REGINALD_COMMIT_LOCK)
	@echo ""
	@echo "==== Installing reginald dependencies into venv... ======================================"
	@echo ""
	$(SILENT) $(REGINALD_PYTHON) -m pip install -r scripts/reginald/requirements.txt
	@echo ""
	@echo "==== Reginald Ready! ===================================================================="
	@echo ""

$(REGINALD_REPO):
	@echo ""
	@echo "==== Installing Reginald: Cloning Reginald repo... ======================================"
	@echo ""
	$(SILENT) git clone git@github.com:schilkp/reginald.git scripts/reginald
	@echo ""
	@echo "==== Setting up python venv... =========================================================="
	@echo ""
	$(SILENT) python -m venv $(REGINALD_REPO)/env
